name: SonarCloud Analysis PR-5887

on:
  workflow_dispatch:  # manual trigger

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: .
          extraProperties: |
            sonar.inclusions=src/compiler/codegen/index.js,src/compiler/codegen/codegenBase.js,src/compiler/parser/index.js
